---
- name: "Restart cache server"
  ansible.builtin.command:
    cmd: "docker compose up -d --force-recreate"
    chdir: >-
      {{ github_actions_self_hosted_runner_install_cache_dir }}
  changed_when: true

- name: "Reload systemd daemon"
  ansible.builtin.systemd:
    daemon_reload: true
  listen: "Restart runner service"

- name: "Restart runner service via svc.sh"
  ansible.builtin.shell:
    cmd: "./svc.sh stop && ./svc.sh start"
    chdir: >-
      {{ github_actions_self_hosted_runner_install_dir }}
  changed_when: true
  listen: "Restart runner service"
