---
- name: "Restart cache server"
  ansible.builtin.command:
    cmd: "docker compose up -d --force-recreate"
    chdir: >-
      {{ github_actions_self_hosted_runner_install_cache_dir }}
  changed_when: true

- name: "Restart runner service"
  ansible.builtin.shell:
    cmd: >-
      systemctl daemon-reload
      && ./svc.sh stop
      && ./svc.sh start
    chdir: >-
      {{ github_actions_self_hosted_runner_install_dir }}
  changed_when: true
