---
- name: "Install rsyslog"
  ansible.builtin.apt:
    name: "rsyslog"
    state: "present"
    update_cache: true

- name: "Ensure rsyslog is enabled and started"
  ansible.builtin.systemd:
    name: "rsyslog"
    state: "started"
    enabled: true
