---
- name: "Reload sasl_passwd db"
  ansible.builtin.command: "postmap /etc/postfix/sasl/sasl_passwd"
  changed_when: true

- name: "Update aliases db"
  ansible.builtin.command: "newaliases"
  changed_when: true

- name: "Restart postfix"
  ansible.builtin.systemd:
    name: "postfix"
    state: "restarted"
    enabled: true
