---
- name: "Validate required variables"
  ansible.builtin.assert:
    that:
      - "postgres_restic_backup_s3_endpoint is defined"
      - "postgres_restic_backup_s3_endpoint | length > 0"
      - "postgres_restic_backup_s3_bucket is defined"
      - "postgres_restic_backup_s3_bucket | length > 0"
      - "postgres_restic_backup_s3_access_key is defined"
      - "postgres_restic_backup_s3_access_key | length > 0"
      - "postgres_restic_backup_s3_secret_key is defined"
      - "postgres_restic_backup_s3_secret_key | length > 0"
      - "postgres_restic_backup_restic_password is defined"
      - "postgres_restic_backup_restic_password | length > 0"
      - "postgres_restic_backup_postgres_user is defined"
      - "postgres_restic_backup_postgres_user | length > 0"
      - "postgres_restic_backup_postgres_container is defined"
      - "postgres_restic_backup_postgres_container | length > 0"
    msg: "Missing a required variable"

- name: "Apply restic_backup role"
  ansible.builtin.include_role:
    name: "restic_backup"
  vars:
    restic_backup_dir: "{{ postgres_restic_backup_dir }}"
    restic_backup_cron_schedule: "{{ postgres_restic_backup_cron_schedule }}"
    restic_backup_cron_timezone: "{{ postgres_restic_backup_cron_timezone }}"
    restic_backup_cron_job_name: "postgres-restic-backup"
    restic_backup_retention_daily: >-
      {{ postgres_restic_backup_retention_daily }}
    restic_backup_retention_weekly: >-
      {{ postgres_restic_backup_retention_weekly }}
    restic_backup_retention_monthly: >-
      {{ postgres_restic_backup_retention_monthly }}
    restic_backup_s3_endpoint: >-
      {{ postgres_restic_backup_s3_endpoint }}
    restic_backup_s3_bucket: >-
      {{ postgres_restic_backup_s3_bucket }}
    restic_backup_s3_access_key: >-
      {{ postgres_restic_backup_s3_access_key }}
    restic_backup_s3_secret_key: >-
      {{ postgres_restic_backup_s3_secret_key }}
    restic_backup_restic_password: >-
      {{ postgres_restic_backup_restic_password }}
    restic_backup_command: >-
      docker exec {{ postgres_restic_backup_postgres_container }}
      pg_dumpall -U {{ postgres_restic_backup_postgres_user }}
      | restic backup --stdin --stdin-filename "pg_dumpall.sql"
