---
# Ansible role to install helpful system tools

- name: "Install system tools"
  ansible.builtin.apt:
    name:
      - "btm"
    state: "present"
    update_cache: true
    cache_valid_time: 3600
  register: "system_tools_apt_result"
  retries: 3
  delay: 10
  until: "system_tools_apt_result is success"
