---
postgres_install_docker_version: "18.3"
postgres_install_docker_dir: "/opt/postgres"
postgres_install_docker_port: 5432
postgres_install_docker_user: "postgres"
postgres_install_docker_data_dir: "/var/lib/postgresql"
postgres_install_docker_container_name: "postgres"
postgres_install_docker_initdb_args: ""
