---
- name: "Validate required variables"
  ansible.builtin.assert:
    that:
      - "restic_backup_s3_endpoint is defined"
      - "restic_backup_s3_endpoint | length > 0"
      - "restic_backup_s3_bucket is defined"
      - "restic_backup_s3_bucket | length > 0"
      - "restic_backup_s3_access_key is defined"
      - "restic_backup_s3_access_key | length > 0"
      - "restic_backup_s3_secret_key is defined"
      - "restic_backup_s3_secret_key | length > 0"
      - "restic_backup_restic_password is defined"
      - "restic_backup_restic_password | length > 0"
      - "restic_backup_backup_command is defined"
      - "restic_backup_backup_command | length > 0"
    msg: "Missing a required variable"

- name: "Install required packages"
  ansible.builtin.apt:
    name:
      - "restic"
      - "cron"
      - "moreutils"
    state: "present"
    update_cache: true

- name: "Create backup directory"
  ansible.builtin.file:
    path: "{{ restic_backup_dir }}"
    state: "directory"
    mode: "0755"

- name: "Deploy environment file"
  ansible.builtin.template:
    src: "env.j2"
    dest: "{{ restic_backup_dir }}/env"
    mode: "0600"

- name: "Deploy backup script"
  ansible.builtin.template:
    src: "backup.sh.j2"
    dest: "{{ restic_backup_dir }}/backup.sh"
    mode: "0700"

- name: "Check if restic repository is initialized"
  ansible.builtin.command:
    cmd: >-
      bash -c
      'source {{ restic_backup_dir }}/env
      && restic snapshots'
  register: "restic_backup_repo_check"
  failed_when: false
  changed_when: false

- name: "Initialize restic repository"
  ansible.builtin.command:
    cmd: >-
      bash -c
      'source {{ restic_backup_dir }}/env
      && restic init'
  when: "restic_backup_repo_check.rc != 0"
  changed_when: true

- name: "Deploy backup cron job"
  ansible.builtin.template:
    src: "cron.j2"
    dest: "/etc/cron.d/{{ restic_backup_cron_job_name }}"
    mode: "0644"
