---
github_actions_self_hosted_runner_install_version: "2.333.1"
github_actions_self_hosted_runner_install_cache_server_version: "latest"
github_actions_self_hosted_runner_install_dir: "/opt/github-runner"
github_actions_self_hosted_runner_install_cache_dir: "/opt/github-runner-cache"
github_actions_self_hosted_runner_install_user: "github-action-runner"
github_actions_self_hosted_runner_install_cache_port: 3000
github_actions_self_hosted_runner_install_labels: []
github_actions_self_hosted_runner_install_runner_group: "Default"
github_actions_self_hosted_runner_install_skip_registration: false
