---
postgres_restic_backup_dir: "/opt/postgres-backup"
postgres_restic_backup_cron_schedule: "0 3 * * *"
postgres_restic_backup_cron_timezone: "UTC"
postgres_restic_backup_retention_daily: 7
postgres_restic_backup_retention_weekly: 4
postgres_restic_backup_retention_monthly: 9999
postgres_restic_backup_postgres_user: >-
  {{ postgres_install_docker_user | default('postgres') }}
postgres_restic_backup_postgres_container: "postgres"
