---
- name: "Validate required variables"
  ansible.builtin.assert:
    that:
      - "system_port_forward_add_description is defined"
      - "system_port_forward_add_internal_port is defined"
      - "system_port_forward_add_external_port is defined"
      - "system_port_forward_add_protocol is defined"
    msg: "Missing a required variable"

- name: "Install required packages"
  ansible.builtin.apt:
    name:
      - "miniupnpc"
      - "cron"
    state: "present"
    update_cache: true
    cache_valid_time: 3600

- name: "Check if port forward already exists"
  ansible.builtin.command:
    cmd: "upnpc -l"
  register: "system_port_forward_add_check"
  changed_when: false
  failed_when: false

- name: "Add port forward"
  ansible.builtin.command:
    argv:
      - "upnpc"
      - "-e"
      - "{{ system_port_forward_add_description }}"
      - "-a"
      - "@"
      - "{{ system_port_forward_add_internal_port }}"
      - "{{ system_port_forward_add_external_port }}"
      - "{{ system_port_forward_add_protocol }}"
  when: >-
    system_port_forward_add_external_port | string
    not in (system_port_forward_add_check.stdout | default(''))
  changed_when: "system_port_forward_add_result.rc == 0"
  failed_when: false
  register: "system_port_forward_add_result"

- name: "Add cron job to refresh port forward"
  vars:
    system_port_forward_add_cron_job: >-
      upnpc
      -e '{{ system_port_forward_add_description }}'
      -a @
      {{ system_port_forward_add_internal_port }}
      {{ system_port_forward_add_external_port }}
      {{ system_port_forward_add_protocol }}
  ansible.builtin.cron:
    name: >-
      upnpc refresh
      {{ system_port_forward_add_external_port }}
      {{ system_port_forward_add_protocol }}
    minute: "{{ system_port_forward_add_refresh_interval }}"
    job: "{{ system_port_forward_add_cron_job }}"
  when: "system_port_forward_add_refresh_cron"
