---
# Test with:
# $ echo "Test email" | mail -s "Postfix test" <recipient_email>
# Check logs with:
# $ systemctl status postfix

- name: "Validate required variables"
  ansible.builtin.assert:
    that:
      - "postfix_relay_host is defined"
      - "postfix_relay_port is defined"
      - "postfix_relay_username is defined"
      - "postfix_relay_password is defined"
      - "postfix_relay_hostname is defined"
      - "postfix_relay_root_alias is defined"
    msg: "Missing a required variable"

- name: "Completely purge all exim4 related packages"
  # Don't need em because we're going with postfix
  ansible.builtin.apt:
    pkg:
      - "exim4"
      - "exim4-base"
      - "exim4-config"
      - "exim4-daemon-light"
      - "exim4-daemon-heavy"
    state: "absent"
    purge: true
    autoremove: true

- name: "Install postfix and dependencies"
  ansible.builtin.apt:
    pkg:
      - "postfix"
      - "libsasl2-modules"
      - "mailutils"
    state: "present"
    update_cache: true
    cache_valid_time: 3600

- name: "Create sasl_passwd file"
  ansible.builtin.template:
    src: "sasl_passwd.j2"
    dest: "/etc/postfix/sasl/sasl_passwd"
    mode: "0600"
  notify:
    - "Reload sasl_passwd db"
    - "Restart postfix"

- name: "Configure postfix main.cf"
  ansible.builtin.template:
    src: "main.cf.j2"
    dest: "/etc/postfix/main.cf"
    mode: "0644"
  notify: "Restart postfix"

- name: "Configure mail aliases"
  ansible.builtin.template:
    src: "aliases.j2"
    dest: "/etc/aliases"
    mode: "0644"
  notify:
    - "Update aliases db"
    - "Restart postfix"
