---
# Required vars:
# restic_backup_s3_endpoint: "s3.ap-southeast-2.amazonaws.com"
# restic_backup_s3_bucket: "my-backups"
# restic_backup_s3_access_key: "AKIA..."
# restic_backup_s3_secret_key: "secret"
# restic_backup_restic_password: "secret"
# restic_backup_dir: "/opt/my-app-backup"
# restic_backup_cron_job_name: "my-app-backup"
# restic_backup_path: "/opt/my-app/data" (used by default restic_backup_command)

restic_backup_cron_schedule: "0 3 * * *"
restic_backup_cron_timezone: "UTC"
restic_backup_retention_daily: 7
restic_backup_retention_weekly: 4
restic_backup_retention_monthly: 9999
restic_backup_forget_group_by: "host,paths"
restic_backup_command: >-
  restic backup {{ restic_backup_path }}
