---
- name: "Validate required variables"
  ansible.builtin.assert:
    that:
      - "system_harden_ssh_public_key is defined"
      - "system_harden_ssh_exclusive_access is defined"
      - "system_harden_ssh_permit_root_login is defined"
      - "system_harden_ssh_permit_password_authentication is defined"
      - "system_harden_ssh_ports is defined"
    msg: "Missing a required variable"

- name: "Install openssh-server"
  ansible.builtin.apt:
    name: "openssh-server"
    state: "present"
    update_cache: true

- name: "Start the ssh service"
  ansible.builtin.systemd:
    name: "ssh"
    state: "started"

- name: "Gather service facts"
  ansible.builtin.service_facts: {}

- name: "Disable and stop ssh.socket"
  ansible.builtin.systemd:
    name: "ssh.socket"
    state: "stopped"
    enabled: false
    masked: true
  when: >-
    'ssh.socket' in ansible_facts.services and
    ansible_facts.services['ssh.socket'].state
    == 'active'

- name: "Set up authorized keys for root user"
  ansible.posix.authorized_key:
    user: "root"
    key: "{{ system_harden_ssh_public_key }}"
    exclusive: "{{ system_harden_ssh_exclusive_access }}"

- name: "Update sshd_config"
  ansible.builtin.template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    backup: true
    validate: "sshd -t -f %s"
    mode: "0644"
  notify: "Reload ssh service"

- name: "Check if iptables is available"
  ansible.builtin.command: "which iptables"
  register: "system_harden_ssh_iptables_check"
  changed_when: false
  failed_when: false

- name: "Allow SSH ports through iptables"
  ansible.builtin.iptables:
    chain: "INPUT"
    protocol: "tcp"
    destination_port: "{{ item }}"
    ctstate: "NEW"
    jump: "ACCEPT"
  loop: "{{ system_harden_ssh_ports }}"
  when: "system_harden_ssh_iptables_check.rc == 0"
  notify: "Save iptables rules"

- name: "Save iptables rules"
  ansible.builtin.command: "netfilter-persistent save"
  when:
    - "system_harden_ssh_iptables_check.rc == 0"
    - "system_harden_ssh_iptables_result.changed"
  changed_when: false
