---
- name: "Reload ssh service"
  ansible.builtin.systemd:
    name: "ssh"
    state: "reloaded"

- name: "Save iptables rules"
  ansible.builtin.command: "netfilter-persistent save"
  changed_when: false
