---
- name: "Validate required variables"
  ansible.builtin.assert:
    that:
      - "router_port_forward_description is defined"
      - "router_port_forward_internal_port is defined"
      - "router_port_forward_external_port is defined"
      - "router_port_forward_protocol is defined"
    msg: "Missing a required variable"

- name: "Install required packages"
  ansible.builtin.apt:
    name:
      - "miniupnpc"
    state: "present"
    update_cache: true
    cache_valid_time: 3600

- name: "Check if port forward already exists"
  ansible.builtin.command:
    cmd: "upnpc -l"
  register: "router_port_forward_check"
  changed_when: false
  failed_when: false

- name: "Add port forward"
  ansible.builtin.command:
    argv:
      - "upnpc"
      - "-e"
      - "{{ router_port_forward_description }}"
      - "-a"
      - "@"
      - "{{ router_port_forward_internal_port }}"
      - "{{ router_port_forward_external_port }}"
      - "{{ router_port_forward_protocol }}"
  when: >-
    router_port_forward_external_port | string
    not in (router_port_forward_check.stdout | default(''))
  changed_when: "router_port_forward_result.rc == 0"
  failed_when: false
  register: "router_port_forward_result"

- name: "Apply system_email_root_service role"
  ansible.builtin.include_role:
    name: "system_email_root_service"
  when: "router_port_forward_refresh_timer"

- name: "Deploy refresh systemd service"
  ansible.builtin.template:
    src: "upnpc-refresh.service.j2"
    dest: >-
      /etc/systemd/system/{{ router_port_forward_unit_name }}.service
    mode: "0644"
  notify: "Restart port forward refresh timer"
  when: "router_port_forward_refresh_timer"

- name: "Deploy refresh systemd timer"
  ansible.builtin.template:
    src: "upnpc-refresh.timer.j2"
    dest: >-
      /etc/systemd/system/{{ router_port_forward_unit_name }}.timer
    mode: "0644"
  notify: "Restart port forward refresh timer"
  when: "router_port_forward_refresh_timer"

- name: "Enable and start refresh timer"
  ansible.builtin.systemd:
    name: "{{ router_port_forward_unit_name }}.timer"
    enabled: true
    state: "started"
    daemon_reload: true
  when: "router_port_forward_refresh_timer"
