---
- name: "Validate required variables"
  ansible.builtin.assert:
    that:
      - "system_grub_timeout is defined"
    msg: "Missing a required variable"

- name: "Set GRUB_TIMEOUT"
  ansible.builtin.lineinfile:
    path: "/etc/default/grub"
    regexp: "^GRUB_TIMEOUT="
    line: "GRUB_TIMEOUT={{ system_grub_timeout }}"
    backup: true
  notify: "Update grub"
