---
name: "continuous integration"

on:
  push:
    branches: ["main"]
  pull_request:

# Run only one CI workflow at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: "jdx/mise-action@v3"
        with:
          cache_key: "mise-{{platform}}-{{version}}-{{file_hash}}"
          version: "2026.3.1"

      - name: "Install dependencies"
        run: "just install"

      - name: "Run linters"
        shell: bash
        run: "just lint"

  test-discover:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.discover.outputs.tests }}
    steps:
      - uses: actions/checkout@v6

      - name: "Discover tests"
        id: discover
        run: |
          tests=$(find tests -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "tests=$tests" >> "$GITHUB_OUTPUT"

  tests-run:
    needs: [test-discover]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.test-discover.outputs.tests) }}
    steps:
      - uses: actions/checkout@v6

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v4

      - name: Import GPG key
        run: echo "${{ secrets.SOPS_GITHUB_ACTIONS_GPG_PRIVATE_KEY }}" | gpg --batch --import

      - uses: "jdx/mise-action@v3"
        with:
          cache_key: "mise-{{platform}}-{{version}}-{{file_hash}}"
          version: "2026.3.1"

      - name: "Enable KVM access"
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
            | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: "Install QEMU and cloud-image tools"
        run: |
          sudo apt-get update
          sudo apt-get install -y genisoimage qemu-utils qemu-system-x86

      - name: "Generate SSH key for tests"
        run: >-
          ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N "" -q

      - name: "Install dependencies"
        run: "just install"

      - name: "Run test: ${{ matrix.test }}"
        run: "just test --no-capture --name ${{ matrix.test }}"

  pass-gate:
    needs: ["lint", "tests-run"]
    runs-on: "ubuntu-latest"
    steps:
      - name: "All checks passed"
        run: |
          echo "All checks passed"
